### ISSUE TITLE
Load the SGX PCKCertChain for validation

### ISSUE THREAD

**Issue by definitelynobody** [profianinc/steward#11]

**Comment by npmccallum** [comment]
I think this is now done. Can you confirm @definitelynobody ?

**Comment by definitelynobody** [comment]
Yeah this issue is done I will push it along with some other stuff today @npmccallum

**Comment by npmccallum** [comment]
@definitelynobody Please retrofit it [into here](https://github.com/profianinc/steward/blob/main/src/ext/sgx/mod.rs). Use the `snp` validator as an example.

**Comment by npmccallum** [comment]
@definitelynobody This issue is done, right? We have [code to validate the cert](https://github.com/profianinc/steward/blob/main/src/ext/sgx/mod.rs#L61) and a [test which checks this](https://github.com/profianinc/steward/blob/main/src/main.rs#L348).

**Comment by definitelynobody** [comment]
Yeah this one is done.
