### ISSUE TITLE
Missing SGX attestation steps

### ISSUE THREAD

**Issue by haraldh** [profianinc/steward#112]
Reading:
https://www.intel.com/content/dam/develop/external/us/en/documents/intel-sgx-support-for-third-party-attestation-801017.pdf
attestation must:
* [x] Verify the integrity of the signature chain from the Quote to the Intel-issued PCK certificate.
* [ ] Verify no keys in the chain have been revoked.
* [x] Verify the Quoting Enclave is from a suitable source and is up to date.
* [ ] Verify the status of the Intel® SGX TCB described in the chain.
* [x] Verify the enclave measurements in the Quote reflect an enclave identity expected.

We currently lack key revocation checks and TCB checks.

**Comment by dpal** [comment]
@rjzak this was triaged as a critical issue, please prioritize.

**Comment by rjzak** [comment]
Scott @ Intel pointed me in this direction, Intel's service for getting CRLs (and other fun stuff) https://api.portal.trustedservices.intel.com/documentation#pcs-certificate-v4.

` curl -v -X GET https://api.trustedservices.intel.com/sgx/certification/v4/pckcrl?ca=platform&encoding=der`

Three questions:
1) Should this be something Steward does occasionally and caches locally? If so, how often?
2) Should this be cached and stored locally, or optional via config? Not all users might have Internet access for routine updates.
3) The other option for `ca=` is `processor`. Should we check both?

**Comment by rjzak** [comment]
Steward will:

* Receive the TCB from Enarx as part of the attestation CSR, https://github.com/enarx/enarx/issues/2380
* Check that:
  * The `fmspc` matches from the attestation report PCK and provided TCB.
  * Check the fields in the TCB to ensure lower or equal values to the `cpusvn`.
  * Check that the TCB report `tcbStatus` field equals `UpToDate`. Example: https://api.portal.trustedservices.intel.com/documentation#pcs-tcb-info-v4

**Comment by haraldh** [comment]
The certificate chain sent with the attestation report contains a PCK cert, which contains all the relevant information in an extension with the OID `1.2.840.113741.1.13.1` already.

It is described in https://api.trustedservices.intel.com/documents/Intel_SGX_PCK_Certificate_CRL_Spec-1.4.pdf
chapter "1.3.5 Intel® SGX PCK Certificate"
