### ISSUE TITLE
Validate SNP response data against signature

### ISSUE THREAD

**Issue by rjzak** [profianinc/steward#6]
Example C code: https://github.com/AMDESE/sev-tool/blob/22c5d4537a124f5ad17e31d54cedc8a9fe933935/src/commands.cpp#L1062
AMD's struct https://github.com/AMDESE/sev-tool/blob/1575ebcd50d6a475cc6c66ad6eb6536760d37592/src/rmp.h#L309-L337
Algo: `SEV_SIG_ALGO_ECDSA_SHA384`

**Comment by npmccallum** [comment]
We now validate the SNP report signature. Closing.
